<?php

namespace Database\Factories;

use App\Models\Category;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Category>
 */
class CategoryFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'parent_id' => null,
            'title' => $this->faker->unique()->randomElement(["Action and adventure", "Art and Architecture", "Alternate history", "Autobiography", "Anthology", "Biography", "Chick lit", "Business and Economics", "Children's", "Crafts and Hobbies", "Classic", "Cookbook","Comic book", "Diary", "Coming-of-age", "Dictionary", "Crime", "Encyclopedia", "Drama", "Guide",  "Fairytale", "Health and Fitness", "Fantasy", "History", "Graphic novel", "Home and garden", "Historical fiction", "Humor", "Horror", "Journal", "Mystery", "Math", "Paranormal romance", "Memoir", "Picture book", "Philosophy", "Poetry", "Prayer", "Political thriller", "Religion, spirituality, and new age", "Romance", "Textbook", "Satire", "True crime", "Science fiction", "Review", "Short story", "Science", "Suspense", "Self help", "Thriller", "Sports and leisure", "Western", "Travel","Young adult", "True crime", "Biography",
            "Classic",
            "Comic",
            "Contemporary",
            "Crime",
            "Drama",
            "Dystopian",
            "Epic",
            "Fairy Tale",
            "Fantasy",
            "Graphic Novel",
            "Historical Fiction",
            "Horror",
            "Humor",
            "Literary Fiction",
            "Magical Realism",
            "Mystery",
            "Mythology",
            "Non-Fiction",
            "Paranormal",
            "Philosophy",
            "Poetry",
            "Political",
            "Psychological Thriller",
            "Religious",
            "Romance",
            "Satire",
            "Science Fiction",
            "Self-Help",
            "Short Story",
            "Suspense",
            "Thriller",
            "Tragedy",
            "Urban",
            "Western",
            "Young Adult",
            "Action",
            "Alternate History",
            "Anthology",
            "Apocalyptic",
            "Autobiography",
            "Chick Lit",
            "Children's",
            "Christian Fiction",
            "Classic Literature",
            "Coming of Age",
            "Cyberpunk",
            "Dark Fantasy",
            "Epic Fantasy",
            "Espionage",
            "Family Saga",
            "Fable",
            "Fairy Tale Retelling",
            "Fan Fiction",
            "Feminist Fiction",
            "Folklore",
            "Gothic",
            "Hard Science Fiction",
            "Heroic Fantasy",
            "Historical Romance",
            "Historical Thriller",
            "Humorous Fiction",
            "Legal Thriller",
            "Light Novel",
            "Literary Criticism",
            "Martial Arts",
            "Media Tie-In",
            "Military Fiction",
            "Military Science Fiction",
            "Mills & Boon",
            "Music",
            "Mythopoeia",
            "Native American",
            "Nature",
            "Noir",
            "Occult",
            "Paranormal Romance",
            "Picture Book",
            "Pirate",
            "Political Thriller",
            "Post-Apocalyptic",
            "Psychological",
            "Pulp",
            "Realistic Fiction",
            "Regency Romance",
            "Religious Fiction",
            "Romantic Comedy",
            "Saga",
            "School Story",
            "Science",
            "Space Opera",
            "Speculative Fiction",
            "Spy Fiction",
            "Steampunk",
            "Superhero",
            "Surrealism",
            "Sword and Sorcery",
            "Techno-Thriller",
            "Time Travel",
            "Tragicomedy",
            "Travel",
            "Urban Fantasy",
            "Victorian",
            "War"]),
            'keywords' => implode(' ', $this->faker->randomElements(["Action and adventure", "Art/architecture", "Alternate history", "Autobiography", "Anthology", "Biography", "Chick lit", "Business/economics", "Children's", "Crafts/hobbies", "Classic", "Cookbook","Comic book", "Diary", "Coming-of-age", "Dictionary", "Crime", "Encyclopedia", "Drama", "Guide",  "Fairytale", "Health/fitness", "Fantasy", "History", "Graphic novel", "Home and garden", "Historical fiction", "Humor", "Horror", "Journal", "Mystery", "Math", "Paranormal romance", "Memoir", "Picture book", "Philosophy", "Poetry", "Prayer", "Political thriller", "Religion, spirituality, and new age", "Romance", "Textbook", "Satire", "True crime", "Science fiction", "Review", "Short story", "Science", "Suspense", "Self help", "Thriller", "Sports and leisure", "Western", "Travel","Young adult", "True crime",     "Adventure",
            "Biography",
            "Classic",
            "Comic",
            "Contemporary",
            "Crime",
            "Drama",
            "Dystopian",
            "Epic",
            "Fairy Tale",
            "Fantasy",
            "Graphic Novel",
            "Historical Fiction",
            "Horror",
            "Humor",
            "Literary Fiction",
            "Magical Realism",
            "Mystery",
            "Mythology",
            "Non-Fiction",
            "Paranormal",
            "Philosophy",
            "Poetry",
            "Political",
            "Psychological Thriller",
            "Religious",
            "Romance",
            "Satire",
            "Science Fiction",
            "Self-Help",
            "Short Story",
            "Suspense",
            "Thriller",
            "Tragedy",
            "Urban",
            "Western",
            "Young Adult",
            "Action",
            "Alternate History",
            "Anthology",
            "Apocalyptic",
            "Autobiography",
            "Chick Lit",
            "Children's",
            "Christian Fiction",
            "Classic Literature",
            "Coming of Age",
            "Cyberpunk",
            "Dark Fantasy",
            "Epic Fantasy",
            "Espionage",
            "Family Saga",
            "Fable",
            "Fairy Tale Retelling",
            "Fan Fiction",
            "Feminist Fiction",
            "Folklore",
            "Gothic",
            "Hard Science Fiction",
            "Heroic Fantasy",
            "Historical Romance",
            "Historical Thriller",
            "Humorous Fiction",
            "Legal Thriller",
            "Light Novel",
            "Literary Criticism",
            "Martial Arts",
            "Media Tie-In",
            "Military Fiction",
            "Military Science Fiction",
            "Mills & Boon",
            "Music",
            "Mythopoeia",
            "Native American",
            "Nature",
            "Noir",
            "Occult",
            "Paranormal Romance",
            "Picture Book",
            "Pirate",
            "Political Thriller",
            "Post-Apocalyptic",
            "Psychological",
            "Pulp",
            "Realistic Fiction",
            "Regency Romance",
            "Religious Fiction",
            "Romantic Comedy",
            "Saga",
            "School Story",
            "Science",
            "Space Opera",
            "Speculative Fiction",
            "Spy Fiction",
            "Steampunk",
            "Superhero",
            "Surrealism",
            "Sword and Sorcery",
            "Techno-Thriller",
            "Time Travel",
            "Tragicomedy",
            "Travel",
            "Urban Fantasy",
            "Victorian",
            "War"], 3)),
            'description' => $this->faker->text(200),
            'image' => '',
            'status' => $this->faker->boolean(90),
        ];
    }
}
